insert into note (title, content, folder_id)
values 
('My Evil Plan', 'this is my maniacl plan to take over the world. I''m baby cloud bread microdosing retro four loko, vape brunch hoodie paleo ethical fashion axe photo booth synth. Seitan synth raclette, dreamcatcher meditation pickled af snackwave butcher.', 3),
('A Note', 'Edison bulb knausgaard chicharrones YOLO hexagon plaid polaroid DIY gastropub tattooed portland pork belly. Lomo +1 you probably haven''t heard of them fanny pack vinyl 8-bit meditation typewriter glossier YOLO seitan freegan tousled.', 2 ),
('Remember', 'Mollit keytar squid, small batch chillwave hashtag incididunt hexagon whatever church-key direct trade meggings mustache schlitz in. Labore literally stumptown waistcoat selvage. Chia food truck skateboard sustainable swag sint echo park single-origin coffee dolore. Skateboard YOLO etsy church-key microdosing food truck', 2),
('To Do List', 'I''m baby beard wayfarers vegan locavore authentic, 3 wolf moon tumblr enim. Hot chicken officia bespoke affogato. Kale chips flexitarian helvetica, enamel pin knausgaard squid microdosing.', 1),
('Blah', 'laid quinoa shabby chic edison bulb typewriter, wayfarers woke listicle do fanny pack taxidermy elit squid mustache. Etsy asymmetrical sint, heirloom flannel enim bitters hexagon pinterest ex non nulla craft beer. Man braid farm-to-table single-origin coffee gochujang. In cred bitters coloring book. Culpa heirloom four dollar toast nulla deserunt readymade man bun adaptogen subway tile enim try-hard. Salvia tumblr lomo prism crucifix, ullamco flannel quis fanny pack. YOLO single-origin coffee migas minim mlkshk.', 1),
('World Domination', 'Fugiat iPhone food truck voluptate nulla whatever. Vegan kombucha deserunt messenger bag, craft beer master cleanse ipsum franzen lo-fi poke disrupt cupidatat tempor synth. Reprehenderit everyday carry four loko, chillwave brooklyn heirloom irure lomo typewriter. Laborum 3 wolf moon green juice cray. Flannel semiotics eiusmod af yr vice enamel pin ut.', 3)
;
